networks:
  bdr-net:
    driver: bridge

services:
  database:
    image: postgres:latest
    container_name: mmo_project_db
    restart: always
    environment:
      POSTGRES_DB: bdr
      POSTGRES_USER: bdr
      POSTGRES_PASSWORD: bdr
      POSTGRES_ROOT_PASSWORD: root
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bdr -d bdr"]
      interval: 3s
      timeout: 10s
      retries: 10
    volumes:
        - ./BDR/scripts/create_database.sql:/docker-entrypoint-initdb.d/01_create_database.sql
        - ./BDR/scripts/Trigger.sql:/docker-entrypoint-initdb.d/02_Trigger.sql
        - ./BDR/scripts/View.sql:/docker-entrypoint-initdb.d/03_View.sql
        - ./BDR/scripts/insert.sql:/docker-entrypoint-initdb.d/04_insert.sql
    networks:
      - bdr-net

  app:
    image: ghcr.io/yoy017/mmo-project:latest
    build:
      context: .
    container_name: mmo_project
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/bdr
      SPRING_DATASOURCE_USERNAME: bdr
      SPRING_DATASOURCE_PASSWORD: bdr
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
    links:
      - database
    networks:
      - bdr-net