<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BDR x DAI</title>
</head>
<body>
<h1>MMO GAME Project</h1>
<p>Welcome to this first template of the MMO GAME Project application.</p>
<p>Here is the current ranking for all Players registered.</p>
<table>
    <tr>
        <th>Name</th>
        <th>Experience</th>
        <th>Balance</th>
        <th>Champion</th>
    </tr>
<%--    @for(player : this.players)--%>
<%--        <tr>--%>
<%--            <td>${player.name}</td>--%>
<%--            <td>${player.experience}</td>--%>
<%--            <td>${player.balance}</td>--%>
<%--            <td>${player.champion}</td>--%>
<%--        </tr>--%>
<%--    @endfor--%>
</table>

<p>Click here to start the game</p>
<button>Play</button>
</body>
</html>